-- Current Date/Time Functions
SELECT CURRENT_DATE;
SELECT CURRENT_TIME;
SELECT CURRENT_TIMESTAMP;
SELECT NOW();

-- Date/Time Extraction Functions
SELECT EXTRACT(YEAR FROM CURRENT_DATE);
SELECT EXTRACT(MONTH FROM CURRENT_DATE);
SELECT EXTRACT(DAY FROM CURRENT_DATE);

SELECT DATE_PART('year', CURRENT_DATE);
SELECT DATE_PART('month', CURRENT_DATE);

-- Date/Time Arithmetic Functions
SELECT AGE(TIMESTAMP '2023-07-11', TIMESTAMP '2020-01-01');

SELECT DATE_TRUNC('month', CURRENT_TIMESTAMP);
SELECT DATE_TRUNC('year', CURRENT_TIMESTAMP);

-- Interval Functions
SELECT JUSTIFY_DAYS(INTERVAL '1000 days');
SELECT JUSTIFY_HOURS(INTERVAL '27 hours');
SELECT JUSTIFY_INTERVAL(INTERVAL '48 hours 1000 minutes');

-- Date/Time Formatting Functions
SELECT TO_CHAR(NOW(), 'YYYY-MM-DD');
SELECT TO_CHAR(NOW(), 'HH24:MI:SS');

SELECT TO_DATE('2024-07-11', 'YYYY-MM-DD');
SELECT TO_TIMESTAMP('2024-07-11 14:30:00', 'YYYY-MM-DD HH24:MI:SS');

-- Miscellaneous Functions
SELECT DATE(NOW());
-- SELECT TIME(NOW());
SELECT ISFINITE('TIMESTAMP' 'infinity');

-- Additional Date/Time Manipulation Functions
-- Date Addition
SELECT CURRENT_DATE + INTERVAL '1 day';
SELECT CURRENT_TIMESTAMP + INTERVAL '2 hours';

-- Date Subtraction
SELECT CURRENT_DATE - INTERVAL '1 day';
SELECT CURRENT_TIMESTAMP - INTERVAL '30 minutes';

-- Adding days, months, and years
SELECT CURRENT_DATE + INTERVAL '10 days';
SELECT CURRENT_DATE + INTERVAL '1 month';
SELECT CURRENT_DATE + INTERVAL '1 year';

-- Subtracting days, months, and years
SELECT CURRENT_DATE - INTERVAL '10 days';
SELECT CURRENT_DATE - INTERVAL '1 month';
SELECT CURRENT_DATE - INTERVAL '1 year';

-- Age calculation
SELECT AGE(NOW(), '1990-01-01'::timestamp);

-- Truncating dates to start of the month, year, etc.
SELECT DATE_TRUNC('day', CURRENT_TIMESTAMP);
SELECT DATE_TRUNC('month', CURRENT_TIMESTAMP);
SELECT DATE_TRUNC('year', CURRENT_TIMESTAMP);

-- Formatting dates
SELECT TO_CHAR(CURRENT_DATE, 'YYYY/MM/DD');
SELECT TO_CHAR(NOW(), 'Day, DD Mon YYYY HH24:MI:SS');

-- Extracting parts of dates
SELECT EXTRACT(DAY FROM CURRENT_TIMESTAMP) AS day;
SELECT EXTRACT(MONTH FROM CURRENT_TIMESTAMP) AS month;
SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP) AS year;
